# Generated by Django 5.1.7 on 2025-03-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
